//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/assets/inputs/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/assets/inputs/PlayerActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Player_moving"",
            ""id"": ""0c50555d-2a94-4c33-93c3-05d237981086"",
            ""actions"": [
                {
                    ""name"": ""MovementX"",
                    ""type"": ""Button"",
                    ""id"": ""8b89e272-5e53-4e29-aa15-12cd0a1dbed6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementZ"",
                    ""type"": ""Button"",
                    ""id"": ""32971c83-344c-40a7-bfad-9a0aab96a18f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""78970bc1-f186-4c7a-a804-b46ecbae6609"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7bda2e73-0b94-40b2-8457-809ef878d8a1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ad51d3ea-8200-4773-9a74-4765e3578277"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e27a8d2b-be53-44a2-ba1f-8f80fed24eda"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""254c6c2d-4bcd-4926-861c-a27beae47b2f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8485e3e7-e149-482c-ab61-b1ed0e06124d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Player_language_attack"",
            ""id"": ""f6f3a057-2ba8-4b7d-9124-f29669404108"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""0ba1c7fc-b660-46c5-bbdc-c27fe07ada48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""11165dc1-c94a-4410-96bc-bf6ddb4e7ecf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player_interaction"",
            ""id"": ""db1c6eba-f804-4eb4-bd75-e0fc4bec97db"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""b2808123-95ea-45cb-83c3-3b68bc63fecd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24c963e7-18aa-444e-9bf6-95388c15f0ca"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_moving
        m_Player_moving = asset.FindActionMap("Player_moving", throwIfNotFound: true);
        m_Player_moving_MovementX = m_Player_moving.FindAction("MovementX", throwIfNotFound: true);
        m_Player_moving_MovementZ = m_Player_moving.FindAction("MovementZ", throwIfNotFound: true);
        // Player_language_attack
        m_Player_language_attack = asset.FindActionMap("Player_language_attack", throwIfNotFound: true);
        m_Player_language_attack_Newaction = m_Player_language_attack.FindAction("New action", throwIfNotFound: true);
        // Player_interaction
        m_Player_interaction = asset.FindActionMap("Player_interaction", throwIfNotFound: true);
        m_Player_interaction_Newaction = m_Player_interaction.FindAction("New action", throwIfNotFound: true);
    }

    ~@PlayerAction()
    {
        UnityEngine.Debug.Assert(!m_Player_moving.enabled, "This will cause a leak and performance issues, PlayerAction.Player_moving.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Player_language_attack.enabled, "This will cause a leak and performance issues, PlayerAction.Player_language_attack.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Player_interaction.enabled, "This will cause a leak and performance issues, PlayerAction.Player_interaction.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_moving
    private readonly InputActionMap m_Player_moving;
    private List<IPlayer_movingActions> m_Player_movingActionsCallbackInterfaces = new List<IPlayer_movingActions>();
    private readonly InputAction m_Player_moving_MovementX;
    private readonly InputAction m_Player_moving_MovementZ;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player_moving".
    /// </summary>
    public struct Player_movingActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player_movingActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player_moving/MovementX".
        /// </summary>
        public InputAction @MovementX => m_Wrapper.m_Player_moving_MovementX;
        /// <summary>
        /// Provides access to the underlying input action "Player_moving/MovementZ".
        /// </summary>
        public InputAction @MovementZ => m_Wrapper.m_Player_moving_MovementZ;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player_moving; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player_movingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player_movingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player_movingActions" />
        public void AddCallbacks(IPlayer_movingActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_movingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_movingActionsCallbackInterfaces.Add(instance);
            @MovementX.started += instance.OnMovementX;
            @MovementX.performed += instance.OnMovementX;
            @MovementX.canceled += instance.OnMovementX;
            @MovementZ.started += instance.OnMovementZ;
            @MovementZ.performed += instance.OnMovementZ;
            @MovementZ.canceled += instance.OnMovementZ;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player_movingActions" />
        private void UnregisterCallbacks(IPlayer_movingActions instance)
        {
            @MovementX.started -= instance.OnMovementX;
            @MovementX.performed -= instance.OnMovementX;
            @MovementX.canceled -= instance.OnMovementX;
            @MovementZ.started -= instance.OnMovementZ;
            @MovementZ.performed -= instance.OnMovementZ;
            @MovementZ.canceled -= instance.OnMovementZ;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player_movingActions.UnregisterCallbacks(IPlayer_movingActions)" />.
        /// </summary>
        /// <seealso cref="Player_movingActions.UnregisterCallbacks(IPlayer_movingActions)" />
        public void RemoveCallbacks(IPlayer_movingActions instance)
        {
            if (m_Wrapper.m_Player_movingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player_movingActions.AddCallbacks(IPlayer_movingActions)" />
        /// <seealso cref="Player_movingActions.RemoveCallbacks(IPlayer_movingActions)" />
        /// <seealso cref="Player_movingActions.UnregisterCallbacks(IPlayer_movingActions)" />
        public void SetCallbacks(IPlayer_movingActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_movingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_movingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player_movingActions" /> instance referencing this action map.
    /// </summary>
    public Player_movingActions @Player_moving => new Player_movingActions(this);

    // Player_language_attack
    private readonly InputActionMap m_Player_language_attack;
    private List<IPlayer_language_attackActions> m_Player_language_attackActionsCallbackInterfaces = new List<IPlayer_language_attackActions>();
    private readonly InputAction m_Player_language_attack_Newaction;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player_language_attack".
    /// </summary>
    public struct Player_language_attackActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player_language_attackActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player_language_attack/Newaction".
        /// </summary>
        public InputAction @Newaction => m_Wrapper.m_Player_language_attack_Newaction;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player_language_attack; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player_language_attackActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player_language_attackActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player_language_attackActions" />
        public void AddCallbacks(IPlayer_language_attackActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_language_attackActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_language_attackActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player_language_attackActions" />
        private void UnregisterCallbacks(IPlayer_language_attackActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player_language_attackActions.UnregisterCallbacks(IPlayer_language_attackActions)" />.
        /// </summary>
        /// <seealso cref="Player_language_attackActions.UnregisterCallbacks(IPlayer_language_attackActions)" />
        public void RemoveCallbacks(IPlayer_language_attackActions instance)
        {
            if (m_Wrapper.m_Player_language_attackActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player_language_attackActions.AddCallbacks(IPlayer_language_attackActions)" />
        /// <seealso cref="Player_language_attackActions.RemoveCallbacks(IPlayer_language_attackActions)" />
        /// <seealso cref="Player_language_attackActions.UnregisterCallbacks(IPlayer_language_attackActions)" />
        public void SetCallbacks(IPlayer_language_attackActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_language_attackActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_language_attackActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player_language_attackActions" /> instance referencing this action map.
    /// </summary>
    public Player_language_attackActions @Player_language_attack => new Player_language_attackActions(this);

    // Player_interaction
    private readonly InputActionMap m_Player_interaction;
    private List<IPlayer_interactionActions> m_Player_interactionActionsCallbackInterfaces = new List<IPlayer_interactionActions>();
    private readonly InputAction m_Player_interaction_Newaction;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player_interaction".
    /// </summary>
    public struct Player_interactionActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player_interactionActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player_interaction/Newaction".
        /// </summary>
        public InputAction @Newaction => m_Wrapper.m_Player_interaction_Newaction;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player_interaction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player_interactionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player_interactionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player_interactionActions" />
        public void AddCallbacks(IPlayer_interactionActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_interactionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_interactionActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player_interactionActions" />
        private void UnregisterCallbacks(IPlayer_interactionActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player_interactionActions.UnregisterCallbacks(IPlayer_interactionActions)" />.
        /// </summary>
        /// <seealso cref="Player_interactionActions.UnregisterCallbacks(IPlayer_interactionActions)" />
        public void RemoveCallbacks(IPlayer_interactionActions instance)
        {
            if (m_Wrapper.m_Player_interactionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player_interactionActions.AddCallbacks(IPlayer_interactionActions)" />
        /// <seealso cref="Player_interactionActions.RemoveCallbacks(IPlayer_interactionActions)" />
        /// <seealso cref="Player_interactionActions.UnregisterCallbacks(IPlayer_interactionActions)" />
        public void SetCallbacks(IPlayer_interactionActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_interactionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_interactionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player_interactionActions" /> instance referencing this action map.
    /// </summary>
    public Player_interactionActions @Player_interaction => new Player_interactionActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player_moving" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player_movingActions.AddCallbacks(IPlayer_movingActions)" />
    /// <seealso cref="Player_movingActions.RemoveCallbacks(IPlayer_movingActions)" />
    public interface IPlayer_movingActions
    {
        /// <summary>
        /// Method invoked when associated input action "MovementX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovementX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MovementZ" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovementZ(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player_language_attack" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player_language_attackActions.AddCallbacks(IPlayer_language_attackActions)" />
    /// <seealso cref="Player_language_attackActions.RemoveCallbacks(IPlayer_language_attackActions)" />
    public interface IPlayer_language_attackActions
    {
        /// <summary>
        /// Method invoked when associated input action "New action" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNewaction(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player_interaction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player_interactionActions.AddCallbacks(IPlayer_interactionActions)" />
    /// <seealso cref="Player_interactionActions.RemoveCallbacks(IPlayer_interactionActions)" />
    public interface IPlayer_interactionActions
    {
        /// <summary>
        /// Method invoked when associated input action "New action" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNewaction(InputAction.CallbackContext context);
    }
}
